syntax = "proto3";

package currency;

// Nuevos mensajes para el desafío GetRate
message RateRequest {
  string from_currency = 1;
  string to_currency = 2;
}

message RateReply {
  double rate = 1;
}

// Mensajes existentes
message ConvertRequest {
  string from_currency = 1;
  string to_currency = 2;
  double amount = 3;
}

message ConvertReply {
  double converted_amount = 1;
  double rate = 2;
  string from_currency = 3;
  string to_currency = 4;
}

message Currency {
  string code = 1;
  string name = 2;
}

message Empty {}

service CurrencyConverter {
  rpc Convert(ConvertRequest) returns (ConvertReply);
  rpc GetRate(RateRequest) returns (RateReply);
  rpc GetSupportedCurrencies(Empty) returns (stream Currency);
  rpc StreamRates(Empty) returns (stream ConvertReply);
}